HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 4
Connection: close
Date: Fri, 06 Aug 2021 22:36:55 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type,repository,Authorization
Access-Control-Allow-Methods: OPTIONS,POST,GET
Access-Control-Allow-Credentials: true

pong
