name: "Composer Require Checker"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  composer-require-checker:
    name: "Composer Require Checker"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer-require-checker

      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Check"
        run: "composer-require-checker check"
