name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:

env:
  default_php: "8.1"
  php_extensions: ""

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x

  coverage:
    name: PHPUnit Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.25.5
        with:
          php-version: ${{ env.default_php }}
          extensions: pcov
          coverage: pcov
          ini-values: pcov.enabled=1
      - uses: "ramsey/composer-install@2.2.0"
      - run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml
        # Env allows smoke tests to run against a real repository
        env:
          PRISMIC_REPOSITORY: ${{ secrets.PRISMIC_REPOSITORY }}
          PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.25.5
        with:
          php-version: ${{ env.default_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}
      - uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "highest"
      - run: composer global config bin-dir /usr/local/bin
      - run: composer global require maglnet/composer-require-checker
      - run: /usr/local/bin/composer-require-checker check

  mutation-tests:
    name: "Mutation Tests"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@2.25.5"
        with:
          coverage: "xdebug"
          php-version: ${{ env.default_php }}
      - uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "highest"
      - run: "vendor/bin/infection --configuration=infection-custom.json"
