name: "Mutation Tests"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  mutation-tests:
    name: "Mutation Tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "7.4"

      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Run mutation tests with Xdebug and infection/infection"
        run: "vendor/bin/infection --configuration=infection.json"
